// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmwhqqcdldlrtpqchyjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptd2hxcWNkbGRscnRwcWNoeWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODU2NTksImV4cCI6MjA3MDE2MTY1OX0.qaB5OV9e_D-ZZGaAE-EUSQvXj4iKum6wjKntRFrr9EY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});